---

version: "2.1"

services:

  nzbhydra2:

    image: lscr.io/linuxserver/nzbhydra2

    container_name: nzbhydra2

    environment:

      - PUID=1000

      - PGID=1000

      - TZ=Europe/London

    volumes:
      - name: storage persistentVolumeClaim: 
        claimName: minio-storage
        readOnly: false

      - /config:/config

      - /downloads:/downloads

    ports:

      - 5076:5076

    restart: unless-stopped
